## Working with HTML
1.  read HTML (read_html)
2.  To HTML (to_html)

In [2]:
import pandas as pd
html = pd.read_html("https://en.wikipedia.org/wiki/Mobile_country_code")  
# what it basically does it reads all the tr(table row),th(table head) etc tags and puts it into a list

In [4]:
print(type(html))
html

<class 'list'>

[   MCC  MNC Brand      Operator       Status Bands (MHz)  \
 0    1    1  TEST  Test network  Operational         any
 1    1    1  TEST  Test network  Operational         any
 2  999   99   NaN  Internal use  Operational         any
 3  999  999   NaN  Internal use  Operational         any

                               References and notes
 0                                              NaN
 1                                              NaN
 2  Internal use in private networks, no roaming[4]
 3  Internal use in private networks, no roaming[4]  ,
      Mobile country code                                    Country ISO 3166  \
 0                    289                                 A Abkhazia    GE-AB
 1                    412                                Afghanistan       AF
 2                    276                                    Albania       AL
 3                    603                                    Algeria       DZ
 4                    544  American Samoa (United States of America)       AS
 ..                   ...                                        ...      ...
 247                  452                                    Vietnam       VN
 248                  543                        W Wallis and Futuna       WF
 249                  421                                    Y Yemen       YE
 250                  645                                   Z Zambia       ZM
 251                  648                                   Zimbabwe       ZW

                                   Mobile network codes National MNC authority  \
 0             List of mobile network codes in Abkhazia                    NaN
 1          List of mobile network codes in Afghanistan                    NaN
 2              List of mobile network codes in Albania                    NaN
 3              List of mobile network codes in Algeria                    NaN
 4       List of mobile network codes in American Samoa                    NaN
 ..                                                 ...                    ...
 247        List of mobile network codes in the Vietnam                    NaN
 248  List of mobile network codes in Wallis and Futuna                    NaN
 249          List of mobile network codes in the Yemen                    NaN
 250             List of mobile network codes in Zambia                    NaN
 251           List of mobile network codes in Zimbabwe                    NaN

                       Remarks
 0    MCC is not listed by ITU
 1                         NaN
 2                         NaN
 3                         NaN
 4                         NaN
 ..                        ...
 247                       NaN
 248                       NaN
 249                       NaN
 250                       NaN
 251                       NaN

 [252 rows x 6 columns],
     MCC  MNC     Brand                  Operator           Status Bands (MHz)  \
 0   901    1       ICO  ICO Satellite Management  Not operational   Satellite
 1   901    2       NaN                Unassigned   Returned spare     Unknown
 2   901    3   Iridium                       NaN      Operational   Satellite
 3   901    4       NaN                Unassigned   Returned spare   Satellite
 4   901    5       NaN      Thuraya RMSS Network      Operational   Satellite
 ..  ...  ...       ...                       ...              ...         ...
 92  901   93       NaN                SkyFive AG          Unknown     Unknown
 93  902    1       NaN        MulteFire Alliance      Operational         LTE
 94  991    1       NaN    World's Global Telecom  Not operational     Unknown
 95  991    2  5G Croco               Orange S.A.  Not operational          5G
 96  991    3       NaN                 Halys SAS  Not operational     Unknown

                                  References and notes
 0                                   MNC withdrawn[49]
 1        Formerly: Sense Communications International
 2                                                 NaN
 3                                Formerly: Globalstar
 4                                                 NaN
 ..                                                ...
 92  [77] split off from Nokia; ground-based networ...
 93                                           [4][104]
 94  temporarily assigned until 15 January 2021[88]...
 95  temporarily assigned until 6 August 2022[106][...
 96  temporary assignment for trial until 5 April 2...

 [97 rows x 7 columns],
    MCC  MNC     Brand                 Operator       Status Bands (MHz)  \
 0  995    1  FonePlus  Sure (Diego Garcia) Ltd  Operational     GSM 900

                                 References and notes
 0  There appears to be no officially assigned MCC...  ,
   .mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar a>span,.mw-parser-output .navbar a>abbr{text-decoration:inherit}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}vteTelecommunications  \
 0                                            History
 1                                           Pioneers
 2                                 Transmission media
 3                     Network topology and switching
 4                                       Multiplexing
 5                                           Concepts
 6                                   Types of network
 7                                   Notable networks
 8                                          Locations
 9  Telecommunication portal  Category  Outline  C...

   .mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar a>span,.mw-parser-output .navbar a>abbr{text-decoration:inherit}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}vteTelecommunications.1  \
 0  Beacon Broadcasting Cable protection system Ca...
 1  Nasir Ahmed Edwin Howard Armstrong Mohamed M. ...
 2  Coaxial cable Fiber-optic communication optica...
 3  Bandwidth Links Nodes terminal Network switchi...
 4  Space-division Frequency-division Time-divisio...
 5  Communication protocol Computer network Data t...
 6  Cellular network Ethernet ISDN LAN Mobile NGN ...
 7  ARPANET BITNET CYCLADES FidoNet Internet Inter...
 8  Africa Americas North South Antarctica Asia Eu...
 9  Telecommunication portal  Category  Outline  C...

   .mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar a>span,.mw-parser-output .navbar a>abbr{text-decoration:inherit}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}vteTelecommunications.2
 0                                                NaN
 1                                                NaN
 2                                                NaN
 3                                                NaN
 4                                                NaN
 5                                                NaN
 6                                                NaN
 7                                                NaN
 8                                                NaN
 9  Telecommunication portal  Category  Outline  C...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ]

In [5]:
html[0]

,MCC,MNC,Brand,Operator,Status,Bands (MHz),References and notes
0,1,1,TEST,Test network,Operational,any,NaN
1,1,1,TEST,Test network,Operational,any,NaN
2,999,99,NaN,Internal use,Operational,any,"Internal use in private networks, no roaming[4]"
3,999,999,NaN,Internal use,Operational,any,"Internal use in private networks, no roaming[4]"

In [8]:
print(type(html[1]))
html[1]

<class 'pandas.core.frame.DataFrame'>

,Mobile country code,Country,ISO 3166,Mobile network codes,National MNC authority,Remarks
0,289,A Abkhazia,GE-AB,List of mobile network codes in Abkhazia,NaN,MCC is not listed by ITU
1,412,Afghanistan,AF,List of mobile network codes in Afghanistan,NaN,NaN
2,276,Albania,AL,List of mobile network codes in Albania,NaN,NaN
3,603,Algeria,DZ,List of mobile network codes in Algeria,NaN,NaN
4,544,American Samoa (United States of America),AS,List of mobile network codes in American Samoa,NaN,NaN
...,...,...,...,...,...,...
247,452,Vietnam,VN,List of mobile network codes in the Vietnam,NaN,NaN
248,543,W Wallis and Futuna,WF,List of mobile network codes in Wallis and Futuna,NaN,NaN
249,421,Y Yemen,YE,List of mobile network codes in the Yemen,NaN,NaN
250,645,Z Zambia,ZM,List of mobile network codes in Zambia,NaN,NaN
251,648,Zimbabwe,ZW,List of mobile network codes in Zimbabwe,NaN,NaN

In [10]:
html1 = pd.read_html("https://en.wikipedia.org/wiki/Economy_of_the_United_States")

In [11]:
html1

[                                                    0  \
 0   New York City, the world’s principal financial...
 1                                            Currency
 2                                         Fiscal year
 3                                 Trade organizations
 4                                       Country group
 5                                          Statistics
 6                                          Population
 7                                                 GDP
 8                                            GDP rank
 9                                          GDP growth
 10                                     GDP per capita
 11                                GDP per capita rank
 12                                      GDP by sector
 13                                   GDP by component
 14                                    Inflation (CPI)
 15                                   Gini coefficient
 16                            Human Development Index
 17                                        Labor force
 18                          Labor force by occupation
 19                                       Unemployment
 20                               Average gross salary
 21                                Median gross salary
 22                                    Main industries
 23                                           External
 24                                            Exports
 25                                       Export goods
 26                               Main export partners
 27                                            Imports
 28                                       Import goods
 29                               Main import partners
 30                                          FDI stock
 31                                    Current account
 32                                Gross external debt
 33                                    Public finances
 34                                        Public debt
 35                                           Revenues
 36                                           Expenses
 37                                       Economic aid
 38                                      Credit rating
 39                                   Foreign reserves
 40  Main data source: CIA World Fact Book All valu...

                                                     1
 0   New York City, the world’s principal financial...
 1          United States dollar (USD) US Dollar Index
 2                October 1, 2021 – September 30, 2022
 3                                WTO, OECD and others
 4        Developed/Advanced[3] High-income economy[4]
 5                                          Statistics
 6                         332,725,203 (2022-06-01)[5]
 7               $24.88 trillion (nominal; 2022)[6][7]
 8                 1st (nominal; 2022) 2nd (PPP; 2022)
 9   –3.4% (2020)[8]  5.7% (2021e)[8]  1.6% (2022f)...
 10                          $76,027 (est 2022)[7][12]
 11                8th (nominal; 2022) 9th (PPP; 2022)
 12  Agriculture: 0.9% Industry: 18.9% Services: 80...
 13  Household consumption: 68.4% Government consum...
 14                         8.3% (August 2022)[14][15]
 15  48.9 high (2020, USCB)[16]  43.4 medium (2017,...
 16  0.926 very high (2019)[18] (17th)  0.808 very ...
 17  164.409 million (March 2022)[20]  62.4% employ...
 18  Agriculture: 1.0% Industry: 19% Services: 80% ...
 19  3.5% (July 2022)[20]  11.5% youth unemployment...
 20                                  $6,738 (2021)[22]
 21                       $1,041 weekly (Q2, 2022)[23]
 22  Petroleumsteelmotor vehiclesaerospacetelecommu...
 23                                           External
 24                         $2.528 trillion (2021)[24]
 25  Agricultural products 10.7%Fuels and mining pr...
 26  European Union(+) 18.7% Canada(+) 18.3% Mexico...
 27                         $3.387 trillion (2021)[24]
 28  Agricultural products 10.5%Fuels and mining pr...
 29  China(-) 21.4% European Union(+) 18.9% Mexico(...
 30  Inward: $156.3 billion (2020)[28]  Outward: $9...
 31                    −$501.3 billion (2020 est.)[30]
 32  $23.4 trillion (December 2021)[31] note: appro...
 33                                    Public finances
 34                        123.5% of GDP (FY 2021)[32]
 35                          $3.42 trillion (2020)[33]
 36                          $6.55 trillion (2020)[34]
 37              donor: ODA, $35.26 billion (2017)[35]
 38  Standard & Poor's:[36][37] AA+ (Domestic) AA+ ...
 39                    $41.8 billion (August 2020)[41]
 40  Main data source: CIA World Fact Book All valu...  ,
                                                    0
 0            This article is part of a series on the
 1                       Economy of the United States
 2  Economic history Agricultural history Banking ...
 3  Sectors Primary sector Agriculture Energy Petr...
 4  Economy by state California Texas New York Flo...
 5  Economy by city or county Allentown Atlanta Bu...
 6  Labor Labor Law  Child labor  Minimum wage Rig...
 7                               United States portal
 8  .mw-parser-output .navbar{display:inline;font-...,
     0                                                  1
 0 NaN  This section needs to be updated. Please help ...,
     Year  GDP (in Bil. US$PPP)  GDP per capita (in US$ PPP)  \
 0   1980                2857.3                      12552.9
 1   1981                3207.0                      13948.7
 2   1982                3343.8                      14405.0
 3   1983                3634.0                      15513.7
 4   1984                4037.7                      17086.4
 5   1985                4339.0                      18199.3
 6   1986                4579.6                      19034.8
 7   1987                4855.3                      20001.0
 8   1988                5236.4                      21376.0
 9   1989                5641.6                      22814.1
 10  1990                5963.1                      23848.0
 11  1991                6158.1                      24302.8
 12  1992                6520.3                      25392.9
 13  1993                6858.6                      26364.2
 14  1994                7287.3                      27674.0
 15  1995                7639.8                      28671.5
 16  1996                8073.1                      29947.0
 17  1997                8577.6                      31440.1
 18  1998                9062.8                      32833.7
 19  1999                9631.2                      34496.2
 20  2000               10251.0                      36312.8
 21  2001               10581.9                      37101.5
 22  2002               10929.1                      37945.8
 23  2003               11456.5                      39405.4
 24  2004               12217.2                      41641.6
 25  2005               13039.2                      44034.3
 26  2006               13815.6                      46216.9
 27  2007               14474.3                      47943.4
 28  2008               14769.9                      48470.6
 29  2009               14478.1                      47102.4
 30  2010               15049.0                      48586.3
 31  2011               15599.7                      50008.1
 32  2012               16254.0                      51736.7
 33  2013               16843.2                      53245.5
 34  2014               17550.7                      55083.5
 35  2015               18206.0                      56729.7
 36  2016               18695.1                      57840.0
 37  2017               19479.6                      59885.7
 38  2018               20527.2                      62769.7
 39  2019               21372.6                      65051.9
 40  2020               20893.8                      63078.5
 41  2021               22996.1                      69227.1
 42  2022               25035.2                      75179.6
 43  2023               26185.2                      78421.9
 44  2024               27057.2                      80779.3
 45  2025               28045.3                      83463.2
 46  2026               29165.5                      86521.2
 47  2027               30281.5                      89546.4

     GDP (in Bil. US$nominal)  GDP per capita (in US$ nominal)  \
 0                     2857.3                          12552.9
 1                     3207.0                          13948.7
 2                     3343.8                          14405.0
 3                     3634.0                          15513.7
 4                     4037.7                          17086.4
 5                     4339.0                          18199.3
 6                     4579.6                          19034.8
 7                     4855.3                          20001.0
 8                     5236.4                          21376.0
 9                     5641.6                          22814.1
 10                    5963.1                          23848.0
 11                    6158.1                          24302.8
 12                    6520.3                          25392.9
 13                    6858.6                          26364.2
 14                    7287.3                          27674.0
 15                    7639.8                          28671.5
 16                    8073.1                          29947.0
 17                    8577.6                          31440.1
 18                    9062.8                          32833.7
 19                    9631.2                          34496.2
 20                   10251.0                          36312.8
 21                   10581.9                          37101.5
 22                   10929.1                          37945.8
 23                   11456.5                          39405.4
 24                   12217.2                          41641.6
 25                   13039.2                          44034.3
 26                   13815.6                          46216.9
 27                   14474.3                          47943.4
 28                   14769.9                          48470.6
 29                   14478.1                          47102.4
 30                   15049.0                          48586.3
 31                   15599.7                          50008.1
 32                   16254.0                          51736.7
 33                   16843.2                          53245.5
 34                   17550.7                          55083.5
 35                   18206.0                          56729.7
 36                   18695.1                          57840.0
 37                   19479.6                          59885.7
 38                   20527.2                          62769.7
 39                   21372.6                          65051.9
 40                   20893.8                          63078.5
 41                   22996.1                          69227.1
 42                   25035.2                          75179.6
 43                   26185.2                          78421.9
 44                   27057.2                          80779.3
 45                   28045.3                          83463.2
 46                   29165.5                          86521.2
 47                   30281.5                          89546.4

    GDP growth (real) Inflation rate (in Percent) Unemployment (in Percent)  \
 0              -0.3%                       13.5%                      7.2%
 1               2.5%                       10.4%                      7.6%
 2              -1.8%                        6.2%                      9.7%
 3               4.6%                        3.2%                      9.6%
 4               7.2%                        4.4%                      7.5%
 5               4.2%                        3.5%                      7.2%
 6               3.5%                        1.9%                      7.0%
 7               3.5%                        3.6%                      6.2%
 8               4.2%                        4.1%                      5.5%
 9               3.7%                        4.8%                      5.3%
 10              1.9%                        5.4%                      5.6%
 11             -0.1%                        4.2%                      6.9%
 12              3.5%                        3.0%                      7.5%
 13              2.8%                        3.0%                      6.9%
 14              4.0%                        2.6%                      6.1%
 15              2.7%                        2.8%                      5.6%
 16              3.8%                        2.9%                      5.4%
 17              4.4%                        2.3%                      4.9%
 18              4.5%                        1.5%                      4.5%
 19              4.8%                        2.2%                      4.2%
 20              4.1%                        3.4%                      4.0%
 21              1.0%                        2.8%                      4.7%
 22              1.7%                        1.6%                      5.8%
 23              2.8%                        2.3%                      6.0%
 24              3.9%                        2.7%                      5.5%
 25              3.5%                        3.4%                      5.1%
 26              2.8%                        3.2%                      4.6%
 27              2.0%                        2.9%                      4.6%
 28              0.1%                        3.8%                      5.8%
 29             -2.6%                       -0.3%                      9.3%
 30              2.7%                        1.6%                      9.6%
 31              1.6%                        3.1%                      8.9%
 32              2.3%                        2.1%                      8.1%
 33              1.8%                        1.5%                      7.4%
 34              2.3%                        1.6%                      6.2%
 35              2.7%                        0.1%                      5.3%
 36              1.7%                        1.3%                      4.9%
 37              2.3%                        2.1%                      4.4%
 38              2.9%                        2.4%                      3.9%
 39              2.3%                        1.8%                      3.7%
 40             -3.4%                        1.2%                      8.1%
 41              5.7%                        4.7%                      5.4%
 42              1.6%                        8.1%                      3.7%
 43              1.0%                        3.5%                      4.6%
 44              1.2%                        2.2%                      5.4%
 45              1.8%                        2.0%                      5.4%
 46              2.1%                        2.0%                      4.9%
 47              1.9%                        2.0%                      4.7%

    Government debt (in % of GDP)
 0                            NaN
 1                            NaN
 2                            NaN
 3                            NaN
 4                            NaN
 5                            NaN
 6                            NaN
 7                            NaN
 8                            NaN
 9                            NaN
 10                           NaN
 11                           NaN
 12                           NaN
 13                           NaN
 14                           NaN
 15                           NaN
 16                           NaN
 17                           NaN
 18                           NaN
 19                           NaN
 20                           NaN
 21                         53.1%
 22                         55.5%
 23                         58.6%
 24                         66.2%
 25                         65.5%
 26                         64.2%
 27                         64.6%
 28                         73.5%
 29                         86.7%
 30                         95.2%
 31                         99.5%
 32                        103.1%
 33                        104.6%
 34                        104.6%
 35                        105.2%
 36                        107.2%
 37                        106.2%
 38                        107.5%
 39                        108.8%
 40                        134.5%
 41                        128.1%
 42                        122.1%
 43                        122.9%
 44                        126.0%
 45                        129.4%
 46                        132.2%
 47                        134.9%  ,
   No. Country/Economy  Real GDP    Agri.    Indus.     Serv.
 0   –           World  60093221  1968215  16453140  38396695
 1   1   United States  15160104   149023   3042332  11518980,
                                          No.  \
 0                                          1
 1  *Percentages from CIA World Factbook[142]

                              Country/Economy  \
 0                              United States
 1  *Percentages from CIA World Factbook[142]

                                  Nominal GDP  \
 0                                   18624450
 1  *Percentages from CIA World Factbook[142]

                                        Agri.  \
 0                                  204868.95
 1  *Percentages from CIA World Factbook[142]

                                       Indus.  \
 0                                  3613143.3
 1  *Percentages from CIA World Factbook[142]

                                        Serv.
 0                                14806437.75
 1  *Percentages from CIA World Factbook[142]  ,
     Year  Wealth (billions in USD)
 0   2006                     67704
 1   2007                     68156
 2   2008                     58070
 3   2009                     60409
 4   2010                     64702
 5   2011                     66457
 6   2012                     72316
 7   2013                     81542
 8   2014                     86927
 9   2015                     89614
 10  2016                     95101
 11  2017                    103484
 12  2018                    104329,
     0                                                  1
 0 NaN  The neutrality of this section is disputed. Re...,
     0                                                  1
 0 NaN  Parts of this article (those related to uninsu...,
    Balance of Trade 2014 (goods only)[373]                                  \
                         Unnamed: 0_level_1   China Euro Area  Japan Mexico
 0                                 Computer  −151.9       3.4   −8.0  −11.0
 1                       Oil, Gas, Minerals     1.9       6.4    2.4  −20.8
 2                           Transportation    10.9     −30.9  −46.2  −59.5
 3                                  Apparel   −56.3      −4.9    0.6   −4.2
 4                     Electrical Equipment   −35.9      −2.4   −4.0   −8.5
 5                      Misc. Manufacturing   −35.3       4.9    2.7   −2.8
 6                                Furniture   −18.3      −1.2    0.0   −1.6
 7                                Machinery   −19.9     −27.0  −18.8    3.9
 8                           Primary Metals    −3.1       3.1   −1.8    1.0
 9                        Fabricated Metals   −17.9      −5.9   −3.5    2.8
 10                                Plastics   −15.7      −1.9   −2.0    5.7
 11                                 Textile   −12.3      −1.1   −0.3    2.8
 12                      Beverages, Tobacco     1.3      −9.9    0.6   −3.3
 13                    Nonmetallic Minerals    −6.1      −1.9   −0.4   −1.2
 14                                   Paper    −2.7       1.2    1.1    4.3
 15                                Chemical    −3.9     −39.5   −1.5   19.1
 16                                    Food     0.7      −3.6    6.1    4.9

In [15]:
# Now Suppose i want to pick a specific table from the website how can i do it ? 
# It is very simple, We will use a prameter called "match" and anything which you think can be unique under the table can be passed into match
html1 = pd.read_html("https://en.wikipedia.org/wiki/Economy_of_the_United_States",match="Government debt")
html1

[    Year  GDP (in Bil. US$PPP)  GDP per capita (in US$ PPP)  \
 0   1980                2857.3                      12552.9
 1   1981                3207.0                      13948.7
 2   1982                3343.8                      14405.0
 3   1983                3634.0                      15513.7
 4   1984                4037.7                      17086.4
 5   1985                4339.0                      18199.3
 6   1986                4579.6                      19034.8
 7   1987                4855.3                      20001.0
 8   1988                5236.4                      21376.0
 9   1989                5641.6                      22814.1
 10  1990                5963.1                      23848.0
 11  1991                6158.1                      24302.8
 12  1992                6520.3                      25392.9
 13  1993                6858.6                      26364.2
 14  1994                7287.3                      27674.0
 15  1995                7639.8                      28671.5
 16  1996                8073.1                      29947.0
 17  1997                8577.6                      31440.1
 18  1998                9062.8                      32833.7
 19  1999                9631.2                      34496.2
 20  2000               10251.0                      36312.8
 21  2001               10581.9                      37101.5
 22  2002               10929.1                      37945.8
 23  2003               11456.5                      39405.4
 24  2004               12217.2                      41641.6
 25  2005               13039.2                      44034.3
 26  2006               13815.6                      46216.9
 27  2007               14474.3                      47943.4
 28  2008               14769.9                      48470.6
 29  2009               14478.1                      47102.4
 30  2010               15049.0                      48586.3
 31  2011               15599.7                      50008.1
 32  2012               16254.0                      51736.7
 33  2013               16843.2                      53245.5
 34  2014               17550.7                      55083.5
 35  2015               18206.0                      56729.7
 36  2016               18695.1                      57840.0
 37  2017               19479.6                      59885.7
 38  2018               20527.2                      62769.7
 39  2019               21372.6                      65051.9
 40  2020               20893.8                      63078.5
 41  2021               22996.1                      69227.1
 42  2022               25035.2                      75179.6
 43  2023               26185.2                      78421.9
 44  2024               27057.2                      80779.3
 45  2025               28045.3                      83463.2
 46  2026               29165.5                      86521.2
 47  2027               30281.5                      89546.4

     GDP (in Bil. US$nominal)  GDP per capita (in US$ nominal)  \
 0                     2857.3                          12552.9
 1                     3207.0                          13948.7
 2                     3343.8                          14405.0
 3                     3634.0                          15513.7
 4                     4037.7                          17086.4
 5                     4339.0                          18199.3
 6                     4579.6                          19034.8
 7                     4855.3                          20001.0
 8                     5236.4                          21376.0
 9                     5641.6                          22814.1
 10                    5963.1                          23848.0
 11                    6158.1                          24302.8
 12                    6520.3                          25392.9
 13                    6858.6                          26364.2
 14                    7287.3                          27674.0
 15                    7639.8                          28671.5
 16                    8073.1                          29947.0
 17                    8577.6                          31440.1
 18                    9062.8                          32833.7
 19                    9631.2                          34496.2
 20                   10251.0                          36312.8
 21                   10581.9                          37101.5
 22                   10929.1                          37945.8
 23                   11456.5                          39405.4
 24                   12217.2                          41641.6
 25                   13039.2                          44034.3
 26                   13815.6                          46216.9
 27                   14474.3                          47943.4
 28                   14769.9                          48470.6
 29                   14478.1                          47102.4
 30                   15049.0                          48586.3
 31                   15599.7                          50008.1
 32                   16254.0                          51736.7
 33                   16843.2                          53245.5
 34                   17550.7                          55083.5
 35                   18206.0                          56729.7
 36                   18695.1                          57840.0
 37                   19479.6                          59885.7
 38                   20527.2                          62769.7
 39                   21372.6                          65051.9
 40                   20893.8                          63078.5
 41                   22996.1                          69227.1
 42                   25035.2                          75179.6
 43                   26185.2                          78421.9
 44                   27057.2                          80779.3
 45                   28045.3                          83463.2
 46                   29165.5                          86521.2
 47                   30281.5                          89546.4

    GDP growth (real) Inflation rate (in Percent) Unemployment (in Percent)  \
 0              -0.3%                       13.5%                      7.2%
 1               2.5%                       10.4%                      7.6%
 2              -1.8%                        6.2%                      9.7%
 3               4.6%                        3.2%                      9.6%
 4               7.2%                        4.4%                      7.5%
 5               4.2%                        3.5%                      7.2%
 6               3.5%                        1.9%                      7.0%
 7               3.5%                        3.6%                      6.2%
 8               4.2%                        4.1%                      5.5%
 9               3.7%                        4.8%                      5.3%
 10              1.9%                        5.4%                      5.6%
 11             -0.1%                        4.2%                      6.9%
 12              3.5%                        3.0%                      7.5%
 13              2.8%                        3.0%                      6.9%
 14              4.0%                        2.6%                      6.1%
 15              2.7%                        2.8%                      5.6%
 16              3.8%                        2.9%                      5.4%
 17              4.4%                        2.3%                      4.9%
 18              4.5%                        1.5%                      4.5%
 19              4.8%                        2.2%                      4.2%
 20              4.1%                        3.4%                      4.0%
 21              1.0%                        2.8%                      4.7%
 22              1.7%                        1.6%                      5.8%
 23              2.8%                        2.3%                      6.0%
 24              3.9%                        2.7%                      5.5%
 25              3.5%                        3.4%                      5.1%
 26              2.8%                        3.2%                      4.6%
 27              2.0%                        2.9%                      4.6%
 28              0.1%                        3.8%                      5.8%
 29             -2.6%                       -0.3%                      9.3%
 30              2.7%                        1.6%                      9.6%
 31              1.6%                        3.1%                      8.9%
 32              2.3%                        2.1%                      8.1%
 33              1.8%                        1.5%                      7.4%
 34              2.3%                        1.6%                      6.2%
 35              2.7%                        0.1%                      5.3%
 36              1.7%                        1.3%                      4.9%
 37              2.3%                        2.1%                      4.4%
 38              2.9%                        2.4%                      3.9%
 39              2.3%                        1.8%                      3.7%
 40             -3.4%                        1.2%                      8.1%
 41              5.7%                        4.7%                      5.4%
 42              1.6%                        8.1%                      3.7%
 43              1.0%                        3.5%                      4.6%
 44              1.2%                        2.2%                      5.4%
 45              1.8%                        2.0%                      5.4%
 46              2.1%                        2.0%                      4.9%
 47              1.9%                        2.0%                      4.7%

    Government debt (in % of GDP)
 0                            NaN
 1                            NaN
 2                            NaN
 3                            NaN
 4                            NaN
 5                            NaN
 6                            NaN
 7                            NaN
 8                            NaN
 9                            NaN
 10                           NaN
 11                           NaN
 12                           NaN
 13                           NaN
 14                           NaN
 15                           NaN
 16                           NaN
 17                           NaN
 18                           NaN
 19                           NaN
 20                           NaN
 21                         53.1%
 22                         55.5%
 23                         58.6%
 24                         66.2%
 25                         65.5%
 26                         64.2%
 27                         64.6%
 28                         73.5%
 29                         86.7%
 30                         95.2%
 31                         99.5%
 32                        103.1%
 33                        104.6%
 34                        104.6%
 35                        105.2%
 36                        107.2%
 37                        106.2%
 38                        107.5%
 39                        108.8%
 40                        134.5%
 41                        128.1%
 42                        122.1%
 43                        122.9%
 44                        126.0%
 45                        129.4%
 46                        132.2%
 47                        134.9%  ]

In [16]:
# since we have a match our html1 dataframe has single table which i can access by 
html1[0]

,Year,GDP (in Bil. US$PPP),GDP per capita (in US$ PPP),GDP (in Bil. US$nominal),GDP per capita (in US$ nominal),GDP growth (real),Inflation rate (in Percent),Unemployment (in Percent),Government debt (in % of GDP)
0,1980,2857.3,12552.9,2857.3,12552.9,-0.3%,13.5%,7.2%,NaN
1,1981,3207.0,13948.7,3207.0,13948.7,2.5%,10.4%,7.6%,NaN
2,1982,3343.8,14405.0,3343.8,14405.0,-1.8%,6.2%,9.7%,NaN
3,1983,3634.0,15513.7,3634.0,15513.7,4.6%,3.2%,9.6%,NaN
4,1984,4037.7,17086.4,4037.7,17086.4,7.2%,4.4%,7.5%,NaN
5,1985,4339.0,18199.3,4339.0,18199.3,4.2%,3.5%,7.2%,NaN
6,1986,4579.6,19034.8,4579.6,19034.8,3.5%,1.9%,7.0%,NaN
7,1987,4855.3,20001.0,4855.3,20001.0,3.5%,3.6%,6.2%,NaN
8,1988,5236.4,21376.0,5236.4,21376.0,4.2%,4.1%,5.5%,NaN
9,1989,5641.6,22814.1,5641.6,22814.1,3.7%,4.8%,5.3%,NaN
10,1990,5963.1,23848.0,5963.1,23848.0,1.9%,5.4%,5.6%,NaN
11,1991,6158.1,24302.8,6158.1,24302.8,-0.1%,4.2%,6.9%,NaN
12,1992,6520.3,25392.9,6520.3,25392.9,3.5%,3.0%,7.5%,NaN
13,1993,6858.6,26364.2,6858.6,26364.2,2.8%,3.0%,6.9%,NaN
14,1994,7287.3,27674.0,7287.3,27674.0,4.0%,2.6%,6.1%,NaN
15,1995,7639.8,28671.5,7639.8,28671.5,2.7%,2.8%,5.6%,NaN
16,1996,8073.1,29947.0,8073.1,29947.0,3.8%,2.9%,5.4%,NaN
17,1997,8577.6,31440.1,8577.6,31440.1,4.4%,2.3%,4.9%,NaN
18,1998,9062.8,32833.7,9062.8,32833.7,4.5%,1.5%,4.5%,NaN
19,1999,9631.2,34496.2,9631.2,34496.2,4.8%,2.2%,4.2%,NaN
20,2000,10251.0,36312.8,10251.0,36312.8,4.1%,3.4%,4.0%,NaN
21,2001,10581.9,37101.5,10581.9,37101.5,1.0%,2.8%,4.7%,53.1%
22,2002,10929.1,37945.8,10929.1,37945.8,1.7%,1.6%,5.8%,55.5%
23,2003,11456.5,39405.4,11456.5,39405.4,2.8%,2.3%,6.0%,58.6%
24,2004,12217.2,41641.6,12217.2,41641.6,3.9%,2.7%,5.5%,66.2%
25,2005,13039.2,44034.3,13039.2,44034.3,3.5%,3.4%,5.1%,65.5%
26,2006,13815.6,46216.9,13815.6,46216.9,2.8%,3.2%,4.6%,64.2%
27,2007,14474.3,47943.4,14474.3,47943.4,2.0%,2.9%,4.6%,64.6%
28,2008,14769.9,48470.6,14769.9,48470.6,0.1%,3.8%,5.8%,73.5%
29,2009,14478.1,47102.4,14478.1,47102.4,-2.6%,-0.3%,9.3%,86.7%
30,2010,15049.0,48586.3,15049.0,48586.3,2.7%,1.6%,9.6%,95.2%
31,2011,15599.7,50008.1,15599.7,50008.1,1.6%,3.1%,8.9%,99.5%
32,2012,16254.0,51736.7,16254.0,51736.7,2.3%,2.1%,8.1%,103.1%
33,2013,16843.2,53245.5,16843.2,53245.5,1.8%,1.5%,7.4%,104.6%
34,2014,17550.7,55083.5,17550.7,55083.5,2.3%,1.6%,6.2%,104.6%
35,2015,18206.0,56729.7,18206.0,56729.7,2.7%,0.1%,5.3%,105.2%
36,2016,18695.1,57840.0,18695.1,57840.0,1.7%,1.3%,4.9%,107.2%
37,2017,19479.6,59885.7,19479.6,59885.7,2.3%,2.1%,4.4%,106.2%
38,2018,20527.2,62769.7,20527.2,62769.7,2.9%,2.4%,3.9%,107.5%
39,2019,21372.6,65051.9,21372.6,65051.9,2.3%,1.8%,3.7%,108.8%
40,2020,20893.8,63078.5,20893.8,63078.5,-3.4%,1.2%,8.1%,134.5%
41,2021,22996.1,69227.1,22996.1,69227.1,5.7%,4.7%,5.4%,128.1%
42,2022,25035.2,75179.6,25035.2,75179.6,1.6%,8.1%,3.7%,122.1%
43,2023,26185.2,78421.9,26185.2,78421.9,1.0%,3.5%,4.6%,122.9%
44,2024,27057.2,80779.3,27057.2,80779.3,1.2%,2.2%,5.4%,126.0%
45,2025,28045.3,83463.2,28045.3,83463.2,1.8%,2.0%,5.4%,129.4%
46,2026,29165.5,86521.2,29165.5,86521.2,2.1%,2.0%,4.9%,132.2%
47,2027,30281.5,89546.4,30281.5,89546.4,1.9%,2.0%,4.7%,134.9%

In [18]:
# Now i want to convert above table to html then it is very simple
html1[0].to_html("myCreatedHtml")